name: COS429-Final-Project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - autopep8=1.6.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.0.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2020.6.20
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.1.0
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.2.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=1.2.0
  - ffmpeg=4.2.2
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2022.2.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.13.1
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.22.1
  - kiwisolver=1.4.4
  - lazy_loader=0.1
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.5.6
  - nbclient=0.7.4
  - nbconvert-core=7.3.1
  - nbformat=5.8.0
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.6.0
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.0
  - ply=3.11
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2023.3
  - pywavelets=1.4.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.29.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.20.0
  - scipy=1.9.3
  - send2trash=1.8.2
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.41.2
  - stack_data=0.6.2
  - terminado=0.17.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.11.2
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cython==3.0.0b2
      - ffmpeg-python==0.2.0
      - future==0.18.3
      - glfw==2.5.9
      - pygame==2.4.0
      - pyopengl==3.1.6
      - pyopengl-accelerate==3.1.6
